### PR TITLE
Webo docker

### PR DESCRIPTION
**Pull request by vlad-ko**
moving local env to docker & docker-compose

### CODE REVIEW

**Comment by azatyan** [comment]
nice! is this work now?
How i can help?

**Comment by vlad-ko** [comment]
still need to do some work to upgrade symfony and get all the components
working together.

if you could help test or help with the upgrade it would be awesome. i'm
just slowly trying to get thing back online, then setup a demo + deployment
pipeline to AWS.

**Comment by azatyan** [comment]
Today i have installed monogodb docker container. 
Now trying to upgrade composer.json to work with symfony 3.4 (one of 2 latest versions)
(Maybe we can use Symfony Flex instead, but the structure of Symfony Flex is different than Standard Symfony). In this stage maybe is okay to be working with php >=7.3.1

**Comment by vlad-ko** [comment]
thank you!
let me know how it goes or if there's anything i can help with, because it
sounds like we are doing the same thing at the moment.
i'm going to pull down `master` and take a look at the latest changes.

i don't know if we can get it working with Flex, because there are so many
differences. but we could try :)

**Pull request merged**
