### PR TITLE
security

### PR DESCRIPTION
**Pull request by lancehaynie**
I am not sure if there is a way with Git to completely remove revisions to really protect the information. However, at least this should hide it out in the open.

### CODE REVIEW

**Comment by vlad-ko** [comment]
It's not a big deal, because that account is useless or fake or probably closed by now :)

But I appreciate your continuous improvements!

**Comment by lancehaynie** [comment]
@vlad-ko of course! If you have any documentation on the PAS system that would be super helpful. I kind of have a hodgepodge of versions going right now. I found version 1.1.0 to be the most stable but I have been taking updates from 1.2.0 and the current master. Also, the Docusign stuff has been a pain for some reason. You guys built the foundation for a great product, kind of sad you stopped working on it. While there is a lot of competition in this space, there are not a lot of good options for RIA's with under $25MM AUM.

**Comment by vlad-ko** [comment]
@lancehaynie  indeed, i wish i had the time and resources to work on this project more. (and i keep telling myself that one day i will...), but at least i'm happy that it's in the open and people can at least look at as foundation. 
I'd be happy to share all the information I have about it with you. We have tons of internal documentation if you can safely share your email address with me, I will give you access to the google drive folder where we have lots of floating documents. also i don't mind doing knowledge share once in a while. 

there are so many uses cases for this platform, because we are not limited by any market or specific security. really we are just a connection between User <-> RIA <-> Custodian. 

i get a lot of requests for adjusting this product for the crypto market, which is very possible.

**Comment by lancehaynie** [comment]
@vlad-ko Sure thing, my email is lance@hayniemail.com... It's floating around the internet so much these days I don't really mind. That is what anti-spam filters are for! I would really appreciate it though, my first step is to get a working copy up and running with no bugs. I don't have a TD Ameritrade account, my custodian is Interactive Brokers. However, step one after getting it all working is to build the PAS to be modular where people can build "plugins" for other custodians. Step two would be upgrading everything out of legacy software. PHP 5.6 will no longer be supported security wise after the end of this year.

**Pull request merged**
