### PR TITLE
Update Vagrant Virtualization using PuPHPET

### PR DESCRIPTION
**Pull request by azatyan**
Hi @vlad-ko @gkobilansky 

I have a updated the vagrant configs, and not it working well without any bugs ))

Please approve.

### CODE REVIEW

**Comment by azatyan** [comment]
Thank you!

**Comment by azatyan** [comment]
We need to merge it :))

**Comment by vlad-ko** [comment]
In the future do you have access to merge? I can add privilege if you don't?

**Comment by azatyan** [comment]
I don't have a write access. Yes, you can add.

**Pull request merged**
